apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: mern-app
type: Opaque
data:
  MONGO_URI: bW9uZ29kYitzcnY6Ly9pZGVzdGE3MDVfZGJfdXNlcjpFbzNLbVZWZk9yUDhlSEhzQGNsdXN0ZXIwLmpyY2dxY3kubW9uZ29kYi5uZXQvcHJvZHVjdHM/YXBwTmFtZT1DbHVzdGVyMA==
